#!/usr/bin/env bash
# Configuring a ufw firewall to block all incoming traffic
#	except for TCP port 22, 80, and 443.

# Install UFW (Uncomplicated Firewall) if it's not already installed
sudo apt install ufw

# Set the default policies
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow incoming traffic on specific ports (22, 80, 443)
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

# Deny all other incoming traffic
sudo ufw deny from any

# Enable the UFW firewall
sudo ufw enable

# Display the UFW status
sudo ufw status verbose
